# Data Cleaning
Clean the data then merge the food_diary and food_details csv files. The food diary contains each food item consumed and the food details contains the nutrition information for each food item.

In [1]:
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
pd.options.display.max_columns = None

In [3]:
daily = pd.read_csv('daily_data.csv')
details = pd.read_csv('food_details.csv')
diary = pd.read_csv('food_diary.csv')

In [4]:
daily.head()

,date,weight,total_calories,excercise_calories,Carbs,Fiber,Starch,Sugars,Net Carbs,Fat,Monounsaturated,Polyunsaturated,Omega-3,Omega-6,Saturated,Trans-Fats,Cholesterol,Protein,Cystine,Histidine,Isoleucine,Leucine,Lysine,Methionine,Phenylalanine,Threonine,Tryptophan,Tyrosine,Valine,B1 (Thiamine),B2 (Riboflavin),B3 (Niacin),B5 (Pantothenic Acid),B6 (Pyridoxine),B12 (Cobalamin),Folate,Vitamin A,Vitamin C,Vitamin D,Vitamin E,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Sodium,Zinc
0,2021-04-01,212.2,1941.8,-84.87,133%,144%,No Target,No Target,131%,41%,No Target,No Target,201%,45%,NaN,NaN,No Target,50%,66%,100%,129%,92%,78%,80%,157%,145%,139%,120%,121%,106%,75%,149%,140%,226%,41667%,125%,209%,440%,833%,55%,119%,177%,379%,271%,173%,254%,131%,208%,91%,174%,266%
1,2021-04-02,211.2,1934.9,-84.81,126%,211%,No Target,No Target,115%,34%,No Target,No Target,260%,42%,NaN,NaN,No Target,58%,81%,130%,139%,107%,95%,89%,191%,166%,143%,103%,140%,142%,89%,104%,119%,283%,3%,166%,75%,371%,0%,93%,295%,237%,676%,307%,294%,369%,160%,230%,120%,177%,82%
2,2021-04-03,210.8,2059.2,-78.76,131%,142%,No Target,No Target,129%,48%,No Target,No Target,187%,81%,NaN,NaN,No Target,61%,37%,138%,168%,125%,91%,87%,196%,161%,176%,154%,144%,60%,80%,66%,141%,153%,41674%,55%,129%,363%,834%,31%,155%,227%,321%,397%,149%,296%,126%,135%,177%,128%,268%
3,2021-04-04,211.2,1924.4,-60.58,140%,258%,No Target,No Target,124%,19%,No Target,No Target,84%,11%,NaN,NaN,No Target,57%,68%,132%,145%,117%,107%,83%,205%,145%,141%,89%,143%,53%,72%,67%,93%,190%,5%,125%,60%,216%,178%,72%,433%,170%,509%,336%,211%,325%,162%,204%,133%,240%,72%
4,2021-04-05,209.4,2216.6,-33.5,164%,233%,No Target,No Target,154%,36%,No Target,No Target,93%,14%,NaN,NaN,No Target,55%,60%,111%,116%,91%,88%,74%,170%,131%,156%,113%,119%,108%,111%,93%,95%,251%,41670%,181%,167%,206%,833%,95%,1238%,161%,392%,345%,257%,430%,127%,192%,94%,138%,271%

In [5]:
details.head()

,date,item,Energy,Alcohol,Caffeine,Water,Carbs,Fiber,Starch,Sugars,Net Carbs,Fat,Monounsaturated,Polyunsaturated,Omega-3,Omega-6,Saturated,Trans-Fats,Cholesterol,Protein,Cystine,Histidine,Isoleucine,Leucine,Lysine,Methionine,Phenylalanine,Threonine,Tryptophan,Tyrosine,Valine,B1 (Thiamine),B2 (Riboflavin),B3 (Niacin),B5 (Pantothenic Acid),B6 (Pyridoxine),B12 (Cobalamin),Folate,Vitamin A,Vitamin C,Vitamin D,Vitamin E,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Sodium,Zinc
0,2021-04-01,Decaf,3%,No Target,No Target,19%,5%,5%,No Target,No Target,5%,2%,No Target,No Target,0%,0%,NaN,NaN,No Target,1%,2%,1%,1%,1%,0%,0%,2%,0%,0%,1%,1%,0%,8%,13%,0%,0%,0%,0%,0%,0%,0%,1%,0%,3%,9%,3%,7%,4%,3%,9%,2%,5%,1%
1,2021-04-01,lemon water,0%,No Target,No Target,52%,1%,0%,No Target,No Target,1%,0%,No Target,No Target,0%,0%,NaN,NaN,No Target,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,1%,1%,0%,1%,1%,0%,2%,0%,21%,0%,0%,0%,6%,22%,0%,5%,0%,1%,1%,0%,5%,2%
2,2021-04-01,Banana Protein Surprise,18%,No Target,No Target,3%,36%,21%,No Target,No Target,38%,2%,No Target,No Target,2%,0%,NaN,NaN,No Target,9%,6%,11%,4%,4%,3%,3%,6%,22%,4%,5%,9%,5%,11%,10%,19%,60%,0%,8%,1%,72%,0%,1%,1%,51%,168%,65%,69%,78%,8%,53%,20%,19%,7%
3,2021-04-01,"Carrots, Cooked From Fresh",2%,No Target,No Target,4%,5%,15%,No Target,No Target,3%,0%,No Target,No Target,0%,0%,NaN,NaN,No Target,1%,13%,4%,6%,4%,4%,3%,6%,15%,4%,4%,4%,8%,5%,6%,7%,14%,0%,5%,142%,6%,0%,10%,17%,5%,3%,6%,4%,10%,6%,10%,2%,6%,3%
4,2021-04-01,"Okra, Cooked from Fresh",2%,No Target,No Target,4%,3%,13%,No Target,No Target,1%,0%,No Target,No Target,0%,0%,NaN,NaN,No Target,2%,4%,4%,7%,5%,4%,4%,7%,6%,6%,10%,7%,18%,7%,9%,7%,18%,0%,18%,3%,29%,0%,3%,53%,12%,15%,6%,14%,20%,7%,6%,1%,1%,6%

In [6]:
diary.head()

,date,item,quantity,unit,calories
0,2021-04-01,Decaf,2,full recipe,75.28
1,2021-04-01,lemon water,2,full recipe,10.56
2,2021-04-01,Banana Protein Surprise,1.25,full recipe,411.86
3,2021-04-01,"Carrots, Cooked From Fresh",2.5,"medium - 6"" to 7"" long",52.5
4,2021-04-01,"Okra, Cooked from Fresh",1,"cup, sliced",35.2

We can see details and daily dataframes have columns that can be removed and columns that can be cleaned up. We will want to remove the "%" and convert the remaining value to integer. We can also join the diary with details.

## Converting datatypes

In [7]:
def not_float(value):
    try:
        f = float(value)
        return False
    except:
        return True
    
def non_float_values(df, col_name):
    return df.loc[df[col_name].apply(not_float), col_name]

def convert_str_to_int(df, col_name):
    try:
        df[col_name] = df[col_name].str.replace(r'[^0-9]', '').astype(int)
    except Exception as e:
        print('Could not convert', col_name)

In [8]:
diary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2110 entries, 0 to 2109
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      2110 non-null   object
 1   item      2110 non-null   object
 2   quantity  2110 non-null   object
 3   unit      2110 non-null   object
 4   calories  2110 non-null   object
dtypes: object(5)
memory usage: 82.5+ KB

No null values

In [11]:
non_float_values(diary, 'quantity')

35          Lunch
93          Lunch
303         Lunch
413        Snacks
598     Breakfast
606     Breakfast
615     Breakfast
624        Snacks
636     Breakfast
655        Snacks
668     Breakfast
776        Snacks
849        Snacks
942        Snacks
1016        Lunch
1017       Dinner
1018       Snacks
1051       Snacks
1055       Snacks
1073       Snacks
1090    Breakfast
1107    Breakfast
1156    Breakfast
1274    Breakfast
1310        Lunch
1346        Lunch
1407       Snacks
1449        Lunch
1509       Snacks
1533        Lunch
1538       Snacks
1541        Lunch
1614    Breakfast
1836    Breakfast
1858       Snacks
1879    Breakfast
Name: quantity, dtype: object

In [12]:
diary[diary.quantity.apply(not_float)].shape

(36, 5)

We can filter these out using the handy ~ operator.

In [13]:
diary = diary[~diary.quantity.apply(not_float)]

In [14]:
diary.shape

(2074, 5)

Now we should be able to convert the column to float

In [15]:
diary['quantity'] = diary.quantity.astype(float)

In [16]:
diary[diary.calories.apply(not_float)]

Empty DataFrame
Columns: [date, item, quantity, unit, calories]
Index: []

In [17]:
diary['calories'] = diary.calories.astype(float)

In [18]:
diary['date'] = pd.to_datetime(diary.date)

In [19]:
diary.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2074 entries, 0 to 2109
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      2074 non-null   datetime64[ns]
 1   item      2074 non-null   object
 2   quantity  2074 non-null   float64
 3   unit      2074 non-null   object
 4   calories  2074 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 97.2+ KB

In [20]:
daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 51 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   133 non-null    object
 1   weight                 133 non-null    float64
 2   total_calories         133 non-null    float64
 3   excercise_calories     133 non-null    object
 4   Carbs                  133 non-null    object
 5   Fiber                  133 non-null    object
 6   Starch                 133 non-null    object
 7   Sugars                 133 non-null    object
 8   Net Carbs              133 non-null    object
 9   Fat                    133 non-null    object
 10  Monounsaturated        133 non-null    object
 11  Polyunsaturated        133 non-null    object
 12  Omega-3                133 non-null    object
 13  Omega-6                133 non-null    object
 14  Saturated              0 non-null      float64
 15  Trans-Fats             0 non-null      float64
 16  Cholesterol            133 non-null    object
 17  Protein                133 non-null    object
 18  Cystine                133 non-null    object
 19  Histidine              133 non-null    object
 20  Isoleucine             133 non-null    object
 21  Leucine                133 non-null    object
 22  Lysine                 133 non-null    object
 23  Methionine             133 non-null    object
 24  Phenylalanine          133 non-null    object
 25  Threonine              133 non-null    object
 26  Tryptophan             133 non-null    object
 27  Tyrosine               133 non-null    object
 28  Valine                 133 non-null    object
 29  B1 (Thiamine)          133 non-null    object
 30  B2 (Riboflavin)        133 non-null    object
 31  B3 (Niacin)            133 non-null    object
 32  B5 (Pantothenic Acid)  133 non-null    object
 33  B6 (Pyridoxine)        133 non-null    object
 34  B12 (Cobalamin)        133 non-null    object
 35  Folate                 133 non-null    object
 36  Vitamin A              133 non-null    object
 37  Vitamin C              133 non-null    object
 38  Vitamin D              133 non-null    object
 39  Vitamin E              133 non-null    object
 40  Vitamin K              133 non-null    object
 41  Calcium                133 non-null    object
 42  Copper                 133 non-null    object
 43  Iron                   133 non-null    object
 44  Magnesium              133 non-null    object
 45  Manganese              133 non-null    object
 46  Phosphorus             133 non-null    object
 47  Potassium              133 non-null    object
 48  Selenium               133 non-null    object
 49  Sodium                 133 non-null    object
 50  Zinc                   133 non-null    object
dtypes: float64(4), object(47)
memory usage: 53.1+ KB

In [21]:
daily['date'] = pd.to_datetime(daily.date)

In [22]:
non_float_values(daily, 'excercise_calories')

7       -14.9-33.5
9       -56.4-23.2
21    -14.72-124.3
22     -124.3-65.2
45      -64.9-43.7
Name: excercise_calories, dtype: object

This occured because I applied the sum function to strings and it concatenated them. We should be able to fix with the eval function. we can also fix the spelling.

In [23]:
daily['exercise_calories'] = daily.excercise_calories.apply(eval)
daily.drop('excercise_calories', axis=1, inplace=True)

We can also drop the columns that had no target

In [24]:
daily.drop(['Starch', 'Sugars', 'Monounsaturated', 'Polyunsaturated', 'Saturated', 'Trans-Fats',
           'Cholesterol'], axis=1, inplace=True)

Now we should be able to convert the remaining columns to integer. For example 123% -> 123

In [25]:
for col in daily.columns[3:43]:
    convert_str_to_int(daily, col)

C:\Users\cablu\AppData\Local\Temp\ipykernel_11964\1677322339.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  df[col_name] = df[col_name].str.replace(r'[^0-9]', '').astype(int)

In [26]:
daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   133 non-null    datetime64[ns]
 1   weight                 133 non-null    float64
 2   total_calories         133 non-null    float64
 3   Carbs                  133 non-null    int32
 4   Fiber                  133 non-null    int32
 5   Net Carbs              133 non-null    int32
 6   Fat                    133 non-null    int32
 7   Omega-3                133 non-null    int32
 8   Omega-6                133 non-null    int32
 9   Protein                133 non-null    int32
 10  Cystine                133 non-null    int32
 11  Histidine              133 non-null    int32
 12  Isoleucine             133 non-null    int32
 13  Leucine                133 non-null    int32
 14  Lysine                 133 non-null    int32
 15  Methionine             133 non-null    int32
 16  Phenylalanine          133 non-null    int32
 17  Threonine              133 non-null    int32
 18  Tryptophan             133 non-null    int32
 19  Tyrosine               133 non-null    int32
 20  Valine                 133 non-null    int32
 21  B1 (Thiamine)          133 non-null    int32
 22  B2 (Riboflavin)        133 non-null    int32
 23  B3 (Niacin)            133 non-null    int32
 24  B5 (Pantothenic Acid)  133 non-null    int32
 25  B6 (Pyridoxine)        133 non-null    int32
 26  B12 (Cobalamin)        133 non-null    int32
 27  Folate                 133 non-null    int32
 28  Vitamin A              133 non-null    int32
 29  Vitamin C              133 non-null    int32
 30  Vitamin D              133 non-null    int32
 31  Vitamin E              133 non-null    int32
 32  Vitamin K              133 non-null    int32
 33  Calcium                133 non-null    int32
 34  Copper                 133 non-null    int32
 35  Iron                   133 non-null    int32
 36  Magnesium              133 non-null    int32
 37  Manganese              133 non-null    int32
 38  Phosphorus             133 non-null    int32
 39  Potassium              133 non-null    int32
 40  Selenium               133 non-null    int32
 41  Sodium                 133 non-null    int32
 42  Zinc                   133 non-null    int32
 43  exercise_calories      133 non-null    float64
dtypes: datetime64[ns](1), float64(3), int32(40)
memory usage: 25.1 KB

One more table to go!

In [27]:
details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2074 entries, 0 to 2073
Data columns (total 53 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   2074 non-null   object
 1   item                   2074 non-null   object
 2   Energy                 2074 non-null   object
 3   Alcohol                2074 non-null   object
 4   Caffeine               2074 non-null   object
 5   Water                  2074 non-null   object
 6   Carbs                  2074 non-null   object
 7   Fiber                  2074 non-null   object
 8   Starch                 2074 non-null   object
 9   Sugars                 2074 non-null   object
 10  Net Carbs              2074 non-null   object
 11  Fat                    2074 non-null   object
 12  Monounsaturated        2074 non-null   object
 13  Polyunsaturated        2074 non-null   object
 14  Omega-3                2074 non-null   object
 15  Omega-6                2074 non-null   object
 16  Saturated              0 non-null      float64
 17  Trans-Fats             0 non-null      float64
 18  Cholesterol            2074 non-null   object
 19  Protein                2074 non-null   object
 20  Cystine                2074 non-null   object
 21  Histidine              2074 non-null   object
 22  Isoleucine             2074 non-null   object
 23  Leucine                2074 non-null   object
 24  Lysine                 2074 non-null   object
 25  Methionine             2074 non-null   object
 26  Phenylalanine          2074 non-null   object
 27  Threonine              2074 non-null   object
 28  Tryptophan             2074 non-null   object
 29  Tyrosine               2074 non-null   object
 30  Valine                 2074 non-null   object
 31  B1 (Thiamine)          2074 non-null   object
 32  B2 (Riboflavin)        2074 non-null   object
 33  B3 (Niacin)            2074 non-null   object
 34  B5 (Pantothenic Acid)  2074 non-null   object
 35  B6 (Pyridoxine)        2074 non-null   object
 36  B12 (Cobalamin)        2074 non-null   object
 37  Folate                 2074 non-null   object
 38  Vitamin A              2074 non-null   object
 39  Vitamin C              2074 non-null   object
 40  Vitamin D              2074 non-null   object
 41  Vitamin E              2074 non-null   object
 42  Vitamin K              2074 non-null   object
 43  Calcium                2074 non-null   object
 44  Copper                 2074 non-null   object
 45  Iron                   2074 non-null   object
 46  Magnesium              2074 non-null   object
 47  Manganese              2074 non-null   object
 48  Phosphorus             2074 non-null   object
 49  Potassium              2074 non-null   object
 50  Selenium               2074 non-null   object
 51  Sodium                 2074 non-null   object
 52  Zinc                   2074 non-null   object
dtypes: float64(2), object(51)
memory usage: 858.9+ KB

In [28]:
details['date'] = pd.to_datetime(details.date)

In [29]:
details.head()

,date,item,Energy,Alcohol,Caffeine,Water,Carbs,Fiber,Starch,Sugars,Net Carbs,Fat,Monounsaturated,Polyunsaturated,Omega-3,Omega-6,Saturated,Trans-Fats,Cholesterol,Protein,Cystine,Histidine,Isoleucine,Leucine,Lysine,Methionine,Phenylalanine,Threonine,Tryptophan,Tyrosine,Valine,B1 (Thiamine),B2 (Riboflavin),B3 (Niacin),B5 (Pantothenic Acid),B6 (Pyridoxine),B12 (Cobalamin),Folate,Vitamin A,Vitamin C,Vitamin D,Vitamin E,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Sodium,Zinc
0,2021-04-01,Decaf,3%,No Target,No Target,19%,5%,5%,No Target,No Target,5%,2%,No Target,No Target,0%,0%,NaN,NaN,No Target,1%,2%,1%,1%,1%,0%,0%,2%,0%,0%,1%,1%,0%,8%,13%,0%,0%,0%,0%,0%,0%,0%,1%,0%,3%,9%,3%,7%,4%,3%,9%,2%,5%,1%
1,2021-04-01,lemon water,0%,No Target,No Target,52%,1%,0%,No Target,No Target,1%,0%,No Target,No Target,0%,0%,NaN,NaN,No Target,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,1%,1%,0%,1%,1%,0%,2%,0%,21%,0%,0%,0%,6%,22%,0%,5%,0%,1%,1%,0%,5%,2%
2,2021-04-01,Banana Protein Surprise,18%,No Target,No Target,3%,36%,21%,No Target,No Target,38%,2%,No Target,No Target,2%,0%,NaN,NaN,No Target,9%,6%,11%,4%,4%,3%,3%,6%,22%,4%,5%,9%,5%,11%,10%,19%,60%,0%,8%,1%,72%,0%,1%,1%,51%,168%,65%,69%,78%,8%,53%,20%,19%,7%
3,2021-04-01,"Carrots, Cooked From Fresh",2%,No Target,No Target,4%,5%,15%,No Target,No Target,3%,0%,No Target,No Target,0%,0%,NaN,NaN,No Target,1%,13%,4%,6%,4%,4%,3%,6%,15%,4%,4%,4%,8%,5%,6%,7%,14%,0%,5%,142%,6%,0%,10%,17%,5%,3%,6%,4%,10%,6%,10%,2%,6%,3%
4,2021-04-01,"Okra, Cooked from Fresh",2%,No Target,No Target,4%,3%,13%,No Target,No Target,1%,0%,No Target,No Target,0%,0%,NaN,NaN,No Target,2%,4%,4%,7%,5%,4%,4%,7%,6%,6%,10%,7%,18%,7%,9%,7%,18%,0%,18%,3%,29%,0%,3%,53%,12%,15%,6%,14%,20%,7%,6%,1%,1%,6%

In [30]:
details.drop(['Alcohol', 'Caffeine', 'Starch', 'Sugars', 'Monounsaturated', 'Polyunsaturated', 'Saturated', 
              'Trans-Fats', 'Cholesterol'],
            axis=1, inplace=True)

In [31]:
for col in details.columns[2:]:
    convert_str_to_int(details, col)

C:\Users\cablu\AppData\Local\Temp\ipykernel_11964\1677322339.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  df[col_name] = df[col_name].str.replace(r'[^0-9]', '').astype(int)

In [32]:
details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2074 entries, 0 to 2073
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   2074 non-null   datetime64[ns]
 1   item                   2074 non-null   object
 2   Energy                 2074 non-null   int32
 3   Water                  2074 non-null   int32
 4   Carbs                  2074 non-null   int32
 5   Fiber                  2074 non-null   int32
 6   Net Carbs              2074 non-null   int32
 7   Fat                    2074 non-null   int32
 8   Omega-3                2074 non-null   int32
 9   Omega-6                2074 non-null   int32
 10  Protein                2074 non-null   int32
 11  Cystine                2074 non-null   int32
 12  Histidine              2074 non-null   int32
 13  Isoleucine             2074 non-null   int32
 14  Leucine                2074 non-null   int32
 15  Lysine                 2074 non-null   int32
 16  Methionine             2074 non-null   int32
 17  Phenylalanine          2074 non-null   int32
 18  Threonine              2074 non-null   int32
 19  Tryptophan             2074 non-null   int32
 20  Tyrosine               2074 non-null   int32
 21  Valine                 2074 non-null   int32
 22  B1 (Thiamine)          2074 non-null   int32
 23  B2 (Riboflavin)        2074 non-null   int32
 24  B3 (Niacin)            2074 non-null   int32
 25  B5 (Pantothenic Acid)  2074 non-null   int32
 26  B6 (Pyridoxine)        2074 non-null   int32
 27  B12 (Cobalamin)        2074 non-null   int32
 28  Folate                 2074 non-null   int32
 29  Vitamin A              2074 non-null   int32
 30  Vitamin C              2074 non-null   int32
 31  Vitamin D              2074 non-null   int32
 32  Vitamin E              2074 non-null   int32
 33  Vitamin K              2074 non-null   int32
 34  Calcium                2074 non-null   int32
 35  Copper                 2074 non-null   int32
 36  Iron                   2074 non-null   int32
 37  Magnesium              2074 non-null   int32
 38  Manganese              2074 non-null   int32
 39  Phosphorus             2074 non-null   int32
 40  Potassium              2074 non-null   int32
 41  Selenium               2074 non-null   int32
 42  Sodium                 2074 non-null   int32
 43  Zinc                   2074 non-null   int32
dtypes: datetime64[ns](1), int32(42), object(1)
memory usage: 372.8+ KB

## Join 2 dataframes

In [33]:
daily_foods = pd.merge(diary, details, on=['date', 'item'])
daily_foods.to_csv('daily_foods_clean.csv', index=None)

In [34]:
daily.to_csv('daily_clean.csv', index=None)

## Data cleaned!
We have two csv files we can work with: daily_food_clean.csv and daily_clean.csv